name: caire
version: '1.2.3'
summary: Content aware image resize library
description: |
  Content aware image resize library
grade: stable
confinement: strict
base: core18
parts:
  caire:
    plugin: go
    source: https://github.com/esimov/caire.git
    go-importpath: github.com/esimov/caire
    build-packages:
      - build-essential
apps:
  caire:
    command: bin/caire
    plugs:
      - home
      - x11
